### ISSUE TITLE
Error in Yii 2.14 HeadersAlreadySentException: Headers already sent

### ISSUE THREAD

**Issue by loveorigami** [asinfotrack/yii2-webshell#1]
About this error here
https://github.com/yiisoft/yii2/search?q=HeadersAlreadySentException&type=Issues

Errror in https://github.com/asinfotrack/yii2-webshell/blob/master/actions/ShellAction.php#L108

**Comment by Isitar** [comment]
Hello
Thanks for reporting, this issue is now fixed with 3b3acedf37551c1ff99e51c57bb217225e0940d0
